### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by Hamza-Azeem1** [chetan6780/Auction-house#1]
hi chetan... this Auction-house project was amazing I am developing one and want to know how to add drag and drop feature for images to display instead of URL.. i look at your code it was amazing.. can u help me with that?

**Comment by chetan6780** [comment]
Hi @Hamza-Azeem1, I am glad you like Auction-house, thank you for reaching out. For drag and drop, If you are using js you can create drag-drop area with HTML or react. You can store your uploaded images in /uploads directory of your server or you can use AWS. There is package in node called multer which will help you in uploading images. I hope it will help.
